export type ProvinceData = {
  name: string;
  districts: string[];
  isHot?: boolean;
};

export const VIETNAM_PROVINCES: ProvinceData[] = [
  // Major Badminton & Urban Hubs first
  {
    name: "Hồ Chí Minh",
    isHot: true,
    districts: [
      "Quận 1",
      "Quận 3",
      "Quận 4",
      "Quận 5",
      "Quận 6",
      "Quận 7",
      "Quận 8",
      "Quận 10",
      "Quận 11",
      "Quận 12",
      "Bình Thạnh",
      "Tân Bình",
      "Tân Phú",
      "Phú Nhuận",
      "Gò Vấp",
      "Bình Tân",
      "TP. Thủ Đức",
      "Hóc Môn",
      "Bình Chánh",
      "Củ Chi",
      "Nhà Bè",
      "Cần Giờ",
    ],
  },
  {
    name: "Hà Nội",
    isHot: true,
    districts: [
      "Ba Đình",
      "Hoàn Kiếm",
      "Tây Hồ",
      "Long Biên",
      "Cầu Giấy",
      "Đống Đa",
      "Hai Bà Trưng",
      "Hoàng Mai",
      "Thanh Xuân",
      "Nam Từ Liêm",
      "Bắc Từ Liêm",
      "Hà Đông",
      "Sơn Tây",
      "Đông Anh",
      "Gia Lâm",
      "Thanh Trì",
      "Sóc Sơn",
      "Mê Linh",
      "Ba Vì",
      "Phúc Thọ",
      "Đan Phượng",
      "Hoài Đức",
      "Quốc Oai",
      "Thạch Thất",
      "Chương Mỹ",
      "Thanh Oai",
      "Thường Tín",
      "Phú Xuyên",
      "Ứng Hòa",
      "Mỹ Đức",
    ],
  },
  {
    name: "Đà Nẵng",
    isHot: true,
    districts: [
      "Hải Châu",
      "Thanh Khê",
      "Sơn Trà",
      "Ngũ Hành Sơn",
      "Liên Chiểu",
      "Cẩm Lệ",
      "Hòa Vang",
      "Hoàng Sa",
    ],
  },
  {
    name: "Bình Dương",
    isHot: true,
    districts: [
      "TP. Thủ Dầu Một",
      "TP. Thuận An",
      "TP. Dĩ An",
      "TP. Tân Uyên",
      "TP. Bến Cát",
      "Bàu Bàng",
      "Bắc Tân Uyên",
      "Dầu Tiếng",
      "Phú Giáo",
    ],
  },
  {
    name: "Đồng Nai",
    isHot: true,
    districts: [
      "TP. Biên Hòa",
      "TP. Long Khánh",
      "Long Thành",
      "Nhơn Trạch",
      "Trảng Bom",
      "Thống Nhất",
      "Vĩnh Cửu",
      "Cẩm Mỹ",
      "Xuân Lộc",
      "Định Quán",
      "Tân Phú",
    ],
  },
  {
    name: "Hải Phòng",
    isHot: true,
    districts: [
      "Hồng Bàng",
      "Ngô Quyền",
      "Lê Chân",
      "Hải An",
      "Kiến An",
      "Đồ Sơn",
      "Dương Kinh",
      "Thủy Nguyên",
      "An Dương",
      "An Lão",
      "Kiến Thụy",
      "Tiên Lãng",
      "Vĩnh Bảo",
      "Cát Hải",
      "Bạch Long Vĩ",
    ],
  },
  {
    name: "Cần Thơ",
    isHot: true,
    districts: [
      "Ninh Kiều",
      "Bình Thủy",
      "Cái Răng",
      "Ô Môn",
      "Thốt Nốt",
      "Phong Điền",
      "Cờ Đỏ",
      "Thới Lai",
      "Vĩnh Thạnh",
    ],
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    isHot: true,
    districts: [
      "TP. Vũng Tàu",
      "TP. Bà Rịa",
      "Thị xã Phú Mỹ",
      "Châu Đức",
      "Côn Đảo",
      "Đất Đỏ",
      "Long Điền",
      "Xuyên Mộc",
    ],
  },
  {
    name: "Khánh Hòa",
    isHot: true,
    districts: [
      "TP. Nha Trang",
      "TP. Cam Ranh",
      "Thị xã Ninh Hòa",
      "Vạn Ninh",
      "Diên Khánh",
      "Khánh Vĩnh",
      "Khánh Sơn",
      "Cam Lâm",
      "Trường Sa",
    ],
  },
  {
    name: "Lâm Đồng",
    isHot: true,
    districts: [
      "TP. Đà Lạt",
      "TP. Bảo Lộc",
      "Bảo Lâm",
      "Cát Tiên",
      "Di Linh",
      "Đạ Huoai",
      "Đạ Tẻh",
      "Đam Rông",
      "Đơn Dương",
      "Đức Trọng",
      "Lạc Dương",
      "Lâm Hà",
    ],
  },
  {
    name: "Quảng Ninh",
    isHot: true,
    districts: [
      "TP. Hạ Long",
      "TP. Cẩm Phả",
      "TP. Móng Cái",
      "TP. Uông Bí",
      "Thị xã Đông Triều",
      "Thị xã Quảng Yên",
      "Vân Đồn",
      "Tiên Yên",
      "Hải Hà",
      "Cô Tô",
      "Đầm Hà",
      "Bình Liêu",
      "Ba Chẽ",
    ],
  },
  {
    name: "Bắc Ninh",
    isHot: true,
    districts: [
      "TP. Bắc Ninh",
      "TP. Từ Sơn",
      "Thị xã Thuận Thành",
      "Thị xã Quế Võ",
      "Yên Phong",
      "Tiên Du",
      "Gia Bình",
      "Lương Tài",
    ],
  },
  {
    name: "Thừa Thiên Huế",
    isHot: true,
    districts: [
      "TP. Huế",
      "Thị xã Hương Thủy",
      "Thị xã Hương Trà",
      "Phú Vang",
      "Phú Lộc",
      "Quảng Điền",
      "A Lưới",
      "Nam Đông",
      "Phong Điền",
    ],
  },
  // Remaining Provinces alphabetically
  {
    name: "An Giang",
    districts: [
      "TP. Long Xuyên",
      "TP. Châu Đốc",
      "Thị xã Tân Châu",
      "Thị xã Tịnh Biên",
      "An Phú",
      "Châu Phú",
      "Châu Thành",
      "Chợ Mới",
      "Phú Tân",
      "Thoại Sơn",
      "Tri Tôn",
    ],
  },
  {
    name: "Bắc Giang",
    districts: [
      "TP. Bắc Giang",
      "Thị xã Việt Yên",
      "Hiệp Hòa",
      "Lạng Giang",
      "Lục Nam",
      "Lục Ngạn",
      "Sơn Động",
      "Tân Yên",
      "Yên Dũng",
      "Yên Thế",
    ],
  },
  {
    name: "Bắc Kạn",
    districts: [
      "TP. Bắc Kạn",
      "Ba Bể",
      "Bạch Thông",
      "Chợ Đồn",
      "Chợ Mới",
      "Na Rì",
      "Ngân Sơn",
      "Pác Nặm",
    ],
  },
  {
    name: "Bạc Liêu",
    districts: [
      "TP. Bạc Liêu",
      "Thị xã Giá Rai",
      "Đông Hải",
      "Hòa Bình",
      "Hồng Dân",
      "Phước Long",
      "Vĩnh Lợi",
    ],
  },
  {
    name: "Bến Tre",
    districts: [
      "TP. Bến Tre",
      "Ba Tri",
      "Bình Đại",
      "Châu Thành",
      "Chợ Lách",
      "Giồng Trôm",
      "Mỏ Cày Bắc",
      "Mỏ Cày Nam",
      "Thạnh Phú",
    ],
  },
  {
    name: "Bình Định",
    districts: [
      "TP. Quy Nhơn",
      "Thị xã An Nhơn",
      "Thị xã Hoài Nhơn",
      "An Lão",
      "Hoài Ân",
      "Phù Cát",
      "Phù Mỹ",
      "Tây Sơn",
      "Tuy Phước",
      "Vân Canh",
      "Vĩnh Thạnh",
    ],
  },
  {
    name: "Bình Phước",
    districts: [
      "TP. Đồng Xoài",
      "Thị xã Bình Long",
      "Thị xã Phước Long",
      "Thị xã Chơn Thành",
      "Bù Đăng",
      "Bù Đốp",
      "Bù Gia Mập",
      "Đồng Phú",
      "Hớn Quản",
      "Lộc Ninh",
      "Phú Riềng",
    ],
  },
  {
    name: "Bình Thuận",
    districts: [
      "TP. Phan Thiết",
      "Thị xã La Gi",
      "Bắc Bình",
      "Đức Linh",
      "Hàm Tân",
      "Hàm Thuận Bắc",
      "Hàm Thuận Nam",
      "Phú Quý",
      "Tánh Linh",
      "Tuy Phong",
    ],
  },
  {
    name: "Cà Mau",
    districts: [
      "TP. Cà Mau",
      "Cái Nước",
      "Đầm Dơi",
      "Năm Căn",
      "Ngọc Hiển",
      "Phú Tân",
      "Thới Bình",
      "Trần Văn Thời",
      "U Minh",
    ],
  },
  {
    name: "Cao Bằng",
    districts: [
      "TP. Cao Bằng",
      "Bảo Lạc",
      "Bảo Lâm",
      "Hạ Lang",
      "Hà Quảng",
      "Hòa An",
      "Nguyên Bình",
      "Quảng Hòa",
      "Thạch An",
      "Trùng Khánh",
    ],
  },
  {
    name: "Đắk Lắk",
    districts: [
      "TP. Buôn Ma Thuột",
      "Thị xã Buôn Hồ",
      "Buôn Đôn",
      "Cư Kuin",
      "Cư M'gar",
      "Ea H'leo",
      "Ea Kar",
      "Ea Súp",
      "Krông Ana",
      "Krông Bông",
      "Krông Búk",
      "Krông Năng",
      "Krông Pắc",
      "Lắk",
      "M'Đrắk",
    ],
  },
  {
    name: "Đắk Nông",
    districts: [
      "TP. Gia Nghĩa",
      "Cư Jút",
      "Đắk Glong",
      "Đắk Mil",
      "Đắk R'lấp",
      "Đắk Song",
      "Krông Nô",
      "Tuy Đức",
    ],
  },
  {
    name: "Điện Biên",
    districts: [
      "TP. Điện Biên Phủ",
      "Thị xã Mường Lay",
      "Điện Biên",
      "Điện Biên Đông",
      "Mường Ảng",
      "Mường Chà",
      "Mường Nhé",
      "Nậm Pồ",
      "Tủa Chùa",
      "Tuần Giáo",
    ],
  },
  {
    name: "Đồng Tháp",
    districts: [
      "TP. Cao Lãnh",
      "TP. Sa Đéc",
      "TP. Hồng Ngự",
      "Huyện Cao Lãnh",
      "Châu Thành",
      "Hồng Ngự",
      "Lai Vung",
      "Lấp Vò",
      "Tam Nông",
      "Tân Hồng",
      "Thanh Bình",
      "Tháp Mười",
    ],
  },
  {
    name: "Gia Lai",
    districts: [
      "TP. Pleiku",
      "Thị xã An Khê",
      "Thị xã Ayun Pa",
      "Chư Păh",
      "Chư Prông",
      "Chư Pưh",
      "Chư Sê",
      "Đắk Đoa",
      "Đắk Pơ",
      "Đức Cơ",
      "Ia Grai",
      "Ia Pa",
      "K'Bang",
      "Kông Chro",
      "Krông Pa",
      "Mang Yang",
      "Phú Thiện",
    ],
  },
  {
    name: "Hà Giang",
    districts: [
      "TP. Hà Giang",
      "Bắc Mê",
      "Bắc Quang",
      "Đồng Văn",
      "Hoàng Su Phì",
      "Mèo Vạc",
      "Quản Bạ",
      "Quang Bình",
      "Vị Xuyên",
      "Xín Mần",
      "Yên Minh",
    ],
  },
  {
    name: "Hà Nam",
    districts: [
      "TP. Phủ Lý",
      "Thị xã Duy Tiên",
      "Bình Lục",
      "Kim Bảng",
      "Lý Nhân",
      "Thanh Liêm",
    ],
  },
  {
    name: "Hà Tĩnh",
    districts: [
      "TP. Hà Tĩnh",
      "Thị xã Hồng Lĩnh",
      "Thị xã Kỳ Anh",
      "Cẩm Xuyên",
      "Can Lộc",
      "Đức Thọ",
      "Hương Khê",
      "Hương Sơn",
      "Kỳ Anh",
      "Lộc Hà",
      "Nghi Xuân",
      "Thạch Hà",
      "Vũ Quang",
    ],
  },
  {
    name: "Hải Dương",
    districts: [
      "TP. Hải Dương",
      "TP. Chí Linh",
      "Thị xã Kinh Môn",
      "Bình Giang",
      "Cẩm Giàng",
      "Gia Lộc",
      "Kim Thành",
      "Nam Sách",
      "Ninh Giang",
      "Thanh Hà",
      "Thanh Miện",
      "Tứ Kỳ",
    ],
  },
  {
    name: "Hậu Giang",
    districts: [
      "TP. Vị Thanh",
      "TP. Ngã Bảy",
      "Thị xã Long Mỹ",
      "Châu Thành",
      "Châu Thành A",
      "Huyện Long Mỹ",
      "Phụng Hiệp",
      "Vị Thủy",
    ],
  },
  {
    name: "Hòa Bình",
    districts: [
      "TP. Hòa Bình",
      "Cao Phong",
      "Đà Bắc",
      "Kim Bôi",
      "Lạc Sơn",
      "Lạc Thủy",
      "Lương Sơn",
      "Mai Châu",
      "Tân Lạc",
      "Yên Thủy",
    ],
  },
  {
    name: "Hưng Yên",
    districts: [
      "TP. Hưng Yên",
      "Thị xã Mỹ Hào",
      "Ân Thi",
      "Khoái Châu",
      "Kim Động",
      "Phù Cừ",
      "Tiên Lữ",
      "Văn Giang",
      "Văn Lâm",
      "Yên Mỹ",
    ],
  },
  {
    name: "Kiên Giang",
    districts: [
      "TP. Rạch Giá",
      "TP. Hà Tiên",
      "TP. Phú Quốc",
      "An Biên",
      "An Minh",
      "Châu Thành",
      "Giang Thành",
      "Giồng Riềng",
      "Gò Quao",
      "Hòn Đất",
      "Kiên Hải",
      "Kiên Lương",
      "Tân Hiệp",
      "U Minh Thượng",
      "Vĩnh Thuận",
    ],
  },
  {
    name: "Kon Tum",
    districts: [
      "TP. Kon Tum",
      "Đắk Glei",
      "Đắk Hà",
      "Đắk Tô",
      "Ia H'Drai",
      "Kon Plông",
      "Kon Rẫy",
      "Ngọc Hồi",
      "Sa Thầy",
      "Tu Mơ Rông",
    ],
  },
  {
    name: "Lai Châu",
    districts: [
      "TP. Lai Châu",
      "Mường Tè",
      "Nậm Nhùn",
      "Phong Thổ",
      "Sìn Hồ",
      "Tam Đường",
      "Tân Uyên",
      "Than Uyên",
    ],
  },
  {
    name: "Lạng Sơn",
    districts: [
      "TP. Lạng Sơn",
      "Bắc Sơn",
      "Bình Gia",
      "Cao Lộc",
      "Chi Lăng",
      "Đình Lập",
      "Hữu Lũng",
      "Lộc Bình",
      "Tràng Định",
      "Văn Lãng",
      "Văn Quan",
    ],
  },
  {
    name: "Lào Cai",
    districts: [
      "TP. Lào Cai",
      "Thị xã Sa Pa",
      "Bát Xát",
      "Bảo Thắng",
      "Bảo Yên",
      "Bắc Hà",
      "Mường Khương",
      "Si Ma Cai",
      "Văn Bàn",
    ],
  },
  {
    name: "Long An",
    districts: [
      "TP. Tân An",
      "Thị xã Kiến Tường",
      "Bến Lức",
      "Cần Đước",
      "Cần Giuộc",
      "Châu Thành",
      "Đức Hòa",
      "Đức Huệ",
      "Mộc Hóa",
      "Tân Hưng",
      "Tân Thạnh",
      "Tân Trụ",
      "Thạnh Hóa",
      "Thủ Thừa",
      "Vĩnh Hưng",
    ],
  },
  {
    name: "Nam Định",
    districts: [
      "TP. Nam Định",
      "Giao Thủy",
      "Hải Hậu",
      "Mỹ Lộc",
      "Nam Trực",
      "Nghĩa Hưng",
      "Trực Ninh",
      "Vụ Bản",
      "Xuân Trường",
      "Ý Yên",
    ],
  },
  {
    name: "Nghệ An",
    districts: [
      "TP. Vinh",
      "Thị xã Cửa Lò",
      "Thị xã Hoàng Mai",
      "Thị xã Thái Hòa",
      "Anh Sơn",
      "Con Cuông",
      "Diễn Châu",
      "Đô Lương",
      "Hưng Nguyên",
      "Kỳ Sơn",
      "Nam Đàn",
      "Nghi Lộc",
      "Nghĩa Đàn",
      "Quế Phong",
      "Quỳ Châu",
      "Quỳ Hợp",
      "Quỳnh Lưu",
      "Tân Kỳ",
      "Thanh Chương",
      "Tương Dương",
      "Yên Thành",
    ],
  },
  {
    name: "Ninh Bình",
    districts: [
      "TP. Ninh Bình",
      "TP. Tam Điệp",
      "Gia Viễn",
      "Hoa Lư",
      "Kim Sơn",
      "Nho Quan",
      "Yên Khánh",
      "Yên Mô",
    ],
  },
  {
    name: "Ninh Thuận",
    districts: [
      "TP. Phan Rang - Tháp Chàm",
      "Bác Ái",
      "Ninh Hải",
      "Ninh Phước",
      "Ninh Sơn",
      "Thuận Bắc",
      "Thuận Nam",
    ],
  },
  {
    name: "Phú Thọ",
    districts: [
      "TP. Việt Trì",
      "Thị xã Phú Thọ",
      "Cẩm Khê",
      "Đoan Hùng",
      "Hạ Hòa",
      "Lâm Thao",
      "Phù Ninh",
      "Tam Nông",
      "Tân Sơn",
      "Thanh Ba",
      "Thanh Sơn",
      "Thanh Thủy",
      "Yên Lập",
    ],
  },
  {
    name: "Phú Yên",
    districts: [
      "TP. Tuy Hòa",
      "Thị xã Sông Cầu",
      "Thị xã Đông Hòa",
      "Đồng Xuân",
      "Phú Hòa",
      "Sơn Hòa",
      "Sông Hinh",
      "Tây Hòa",
      "Tuy An",
    ],
  },
  {
    name: "Quảng Bình",
    districts: [
      "TP. Đồng Hới",
      "Thị xã Ba Đồn",
      "Bố Trạch",
      "Lệ Thủy",
      "Minh Hóa",
      "Quảng Ninh",
      "Quảng Trạch",
      "Tuyên Hóa",
    ],
  },
  {
    name: "Quảng Nam",
    districts: [
      "TP. Tam Kỳ",
      "TP. Hội An",
      "Thị xã Điện Bàn",
      "Bắc Trà My",
      "Đại Lộc",
      "Đông Giang",
      "Duy Xuyên",
      "Hiệp Đức",
      "Nam Giang",
      "Nam Trà My",
      "Nông Sơn",
      "Núi Thành",
      "Phú Ninh",
      "Phước Sơn",
      "Quế Sơn",
      "Tây Giang",
      "Thăng Bình",
      "Tiên Phước",
    ],
  },
  {
    name: "Quảng Ngãi",
    districts: [
      "TP. Quảng Ngãi",
      "Thị xã Đức Phổ",
      "Ba Tơ",
      "Bình Sơn",
      "Lý Sơn",
      "Minh Long",
      "Mộ Đức",
      "Nghĩa Hành",
      "Sơn Hà",
      "Sơn Tây",
      "Sơn Tịnh",
      "Trà Bồng",
      "Tư Nghĩa",
    ],
  },
  {
    name: "Quảng Trị",
    districts: [
      "TP. Đông Hà",
      "Thị xã Quảng Trị",
      "Cam Lộ",
      "Cồn Cỏ",
      "Đakrông",
      "Gio Linh",
      "Hải Lăng",
      "Hướng Hóa",
      "Triệu Phong",
      "Vĩnh Linh",
    ],
  },
  {
    name: "Sóc Trăng",
    districts: [
      "TP. Sóc Trăng",
      "Thị xã Ngã Năm",
      "Thị xã Vĩnh Châu",
      "Châu Thành",
      "Cù Lao Dung",
      "Kế Sách",
      "Long Phú",
      "Mỹ Tú",
      "Mỹ Xuyên",
      "Thạnh Trị",
      "Trần Đề",
    ],
  },
  {
    name: "Sơn La",
    districts: [
      "TP. Sơn La",
      "Bắc Yên",
      "Mai Sơn",
      "Mộc Châu",
      "Mường La",
      "Phù Yên",
      "Quỳnh Nhai",
      "Sông Mã",
      "Sốp Cộp",
      "Thuận Châu",
      "Vân Hồ",
      "Yên Châu",
    ],
  },
  {
    name: "Tây Ninh",
    districts: [
      "TP. Tây Ninh",
      "Thị xã Hòa Thành",
      "Thị xã Trảng Bàng",
      "Bến Cầu",
      "Châu Thành",
      "Dương Minh Châu",
      "Gò Dầu",
      "Tân Biên",
      "Tân Châu",
    ],
  },
  {
    name: "Thái Bình",
    districts: [
      "TP. Thái Bình",
      "Đông Hưng",
      "Hưng Hà",
      "Kiến Xương",
      "Quỳnh Phụ",
      "Thái Thụy",
      "Tiền Hải",
      "Vũ Thư",
    ],
  },
  {
    name: "Thái Nguyên",
    districts: [
      "TP. Thái Nguyên",
      "TP. Sông Công",
      "TP. Phổ Yên",
      "Đại Từ",
      "Định Hóa",
      "Đồng Hỷ",
      "Phú Bình",
      "Phú Lương",
      "Võ Nhai",
    ],
  },
  {
    name: "Thanh Hóa",
    districts: [
      "TP. Thanh Hóa",
      "TP. Sầm Sơn",
      "Thị xã Bỉm Sơn",
      "Thị xã Nghi Sơn",
      "Bá Thước",
      "Cẩm Thủy",
      "Đông Sơn",
      "Hà Trung",
      "Hậu Lộc",
      "Hoằng Hóa",
      "Lang Chánh",
      "Mường Lát",
      "Nga Sơn",
      "Ngọc Lặc",
      "Như Thanh",
      "Như Xuân",
      "Nông Cống",
      "Quan Hóa",
      "Quan Sơn",
      "Quảng Xương",
      "Thạch Thành",
      "Thiệu Hóa",
      "Thọ Xuân",
      "Thường Xuân",
      "Triệu Sơn",
      "Vĩnh Lộc",
      "Yên Định",
    ],
  },
  {
    name: "Tiền Giang",
    districts: [
      "TP. Mỹ Tho",
      "Thị xã Gò Công",
      "Thị xã Cai Lậy",
      "Huyện Cai Lậy",
      "Châu Thành",
      "Chợ Gạo",
      "Gò Công Đông",
      "Gò Công Tây",
      "Tân Phú Đông",
      "Tân Phước",
    ],
  },
  {
    name: "Trà Vinh",
    districts: [
      "TP. Trà Vinh",
      "Thị xã Duyên Hải",
      "Càng Long",
      "Cầu Kè",
      "Cầu Ngang",
      "Châu Thành",
      "Huyện Duyên Hải",
      "Tiểu Cần",
      "Trà Cú",
    ],
  },
  {
    name: "Tuyên Quang",
    districts: [
      "TP. Tuyên Quang",
      "Chiêm Hóa",
      "Hàm Yên",
      "Lâm Bình",
      "Na Hang",
      "Sơn Dương",
      "Yên Sơn",
    ],
  },
  {
    name: "Vĩnh Long",
    districts: [
      "TP. Vĩnh Long",
      "Thị xã Bình Minh",
      "Bình Tân",
      "Long Hồ",
      "Mang Thít",
      "Tam Bình",
      "Trà Ôn",
      "Vũng Liêm",
    ],
  },
  {
    name: "Vĩnh Phúc",
    districts: [
      "TP. Vĩnh Yên",
      "TP. Phúc Yên",
      "Bình Xuyên",
      "Lập Thạch",
      "Sông Lô",
      "Tam Đảo",
      "Tam Dương",
      "Vĩnh Tường",
      "Yên Lạc",
    ],
  },
  {
    name: "Yên Bái",
    districts: [
      "TP. Yên Bái",
      "Thị xã Nghĩa Lộ",
      "Lục Yên",
      "Mù Cang Chải",
      "Trạm Tấu",
      "Trấn Yên",
      "Văn Chấn",
      "Văn Yên",
      "Yên Bình",
    ],
  },
];

export const DEFAULT_PROVINCE = "Hồ Chí Minh";
export const DEFAULT_DISTRICT = "Quận 10";

export function getProvinces(): string[] {
  return VIETNAM_PROVINCES.map((p) => p.name);
}

export function getDistricts(provinceName?: string): string[] {
  if (!provinceName) {
    const found = VIETNAM_PROVINCES.find((p) => p.name === DEFAULT_PROVINCE);
    return found ? found.districts : [];
  }
  const cleanName = provinceName.toLowerCase().replace(/^(tp\.?|tỉnh)\s+/i, "").trim();
  const found = VIETNAM_PROVINCES.find(
    (p) =>
      p.name.toLowerCase() === cleanName ||
      p.name.toLowerCase().includes(cleanName) ||
      cleanName.includes(p.name.toLowerCase()),
  );
  return found ? found.districts : [];
}
